// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzs6vgjU0KfQjR9dHvgVQk-N3QBj7qLA8',
    appId: '1:833202912860:web:168fb051b5c1d3183fb099',
    messagingSenderId: '833202912860',
    projectId: 'flash-chat-71225',
    authDomain: 'flash-chat-71225.firebaseapp.com',
    storageBucket: 'flash-chat-71225.firebasestorage.app',
    measurementId: 'G-DXP85KF1TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwZJCVEsH-rZuXTVGkyY5Dugmqn-ZQQ00',
    appId: '1:833202912860:android:7fc98a96dafb3c943fb099',
    messagingSenderId: '833202912860',
    projectId: 'flash-chat-71225',
    storageBucket: 'flash-chat-71225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvyd6zKVI9_W8Gy-dTXYtIxpyqRhBKQc',
    appId: '1:833202912860:ios:bccd33b0bf6d69c73fb099',
    messagingSenderId: '833202912860',
    projectId: 'flash-chat-71225',
    storageBucket: 'flash-chat-71225.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyvyd6zKVI9_W8Gy-dTXYtIxpyqRhBKQc',
    appId: '1:833202912860:ios:bccd33b0bf6d69c73fb099',
    messagingSenderId: '833202912860',
    projectId: 'flash-chat-71225',
    storageBucket: 'flash-chat-71225.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzs6vgjU0KfQjR9dHvgVQk-N3QBj7qLA8',
    appId: '1:833202912860:web:2726cc3b9f2053883fb099',
    messagingSenderId: '833202912860',
    projectId: 'flash-chat-71225',
    authDomain: 'flash-chat-71225.firebaseapp.com',
    storageBucket: 'flash-chat-71225.firebasestorage.app',
    measurementId: 'G-MZGGX74MB6',
  );
}
